"""fix nullable placement in decision_history

Revision ID: 7616c75579e0
Revises: bbea1351f90f
Create Date: 2026-04-13 17:55:58.954228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7616c75579e0'
down_revision: Union[str, Sequence[str], None] = 'bbea1351f90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('decision_histories_decision_id_fkey'), 'decision_histories', type_='foreignkey')
    op.create_foreign_key(None, 'decision_histories', 'decisions', ['decision_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decision_histories', type_='foreignkey')
    op.create_foreign_key(op.f('decision_histories_decision_id_fkey'), 'decision_histories', 'decisions', ['decision_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
