"""fix decision_history FK remove cascade/set null

Revision ID: 76746c554654
Revises: 7616c75579e0
Create Date: 2026-04-13 18:01:54.055841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76746c554654'
down_revision: Union[str, Sequence[str], None] = '7616c75579e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('decision_histories', 'decision_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('decision_histories_decision_id_fkey'), 'decision_histories', type_='foreignkey')
    op.create_foreign_key(None, 'decision_histories', 'decisions', ['decision_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decision_histories', type_='foreignkey')
    op.create_foreign_key(op.f('decision_histories_decision_id_fkey'), 'decision_histories', 'decisions', ['decision_id'], ['id'], ondelete='SET NULL')
    op.alter_column('decision_histories', 'decision_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
