"""add cascade delete to decision history

Revision ID: bbea1351f90f
Revises: 80d951f1ea7a
Create Date: 2026-04-13 17:44:26.756608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbea1351f90f'
down_revision: Union[str, Sequence[str], None] = '80d951f1ea7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('decision_histories_decision_id_fkey'), 'decision_histories', type_='foreignkey')
    op.create_foreign_key(None, 'decision_histories', 'decisions', ['decision_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decision_histories', type_='foreignkey')
    op.create_foreign_key(op.f('decision_histories_decision_id_fkey'), 'decision_histories', 'decisions', ['decision_id'], ['id'])
    # ### end Alembic commands ###
